<a href="https://colab.research.google.com/github/cmason30/colab-practice/blob/master/numpy_ops_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
#look up numpy universal operations

In [0]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr + arr
#adds two arrays with eachother

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [0]:
arr * arr

In [0]:
arr / arr

In [0]:
1/ arr

In [0]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [0]:
np.exp(arr)